/**
 * An enum containing most of the key codes from event.code.
 * This is here to easily get autocomplete info for all keycodes.
 *
 * @memberof ESSEM
 */
export enum KeyCode {
    Unidentified = "Unidentified",

    // printable keys
    Digit1 = "Digit1",
    Digit2 = "Digit2",
    Digit3 = "Digit3",
    Digit4 = "Digit4",
    Digit5 = "Digit5",
    Digit6 = "Digit6",
    Digit7 = "Digit7",
    Digit8 = "Digit8",
    Digit9 = "Digit9",
    Digit0 = "Digit0",

    KeyA = "KeyA",
    KeyB = "KeyB",
    KeyC = "KeyC",
    KeyD = "KeyD",
    KeyE = "KeyE",
    KeyF = "KeyF",
    KeyG = "KeyG",
    KeyH = "KeyH",
    KeyI = "KeyI",
    KeyJ = "KeyJ",
    KeyK = "KeyK",
    KeyL = "KeyL",
    KeyM = "KeyM",
    KeyN = "KeyN",
    KeyO = "KeyO",
    KeyP = "KeyP",
    KeyQ = "KeyQ",
    KeyR = "KeyR",
    KeyS = "KeyS",
    KeyT = "KeyT",
    KeyU = "KeyU",
    KeyV = "KeyV",
    KeyW = "KeyW",
    KeyX = "KeyX",
    KeyY = "KeyY",
    KeyZ = "KeyZ",

    Backquote = "Backquote",
    Backslash = "Backslash",
    Comma = "Comma",
    Equal = "Equal",
    GraveAccent = "GraveAccent",
    LeftBracket = "LeftBracket",
    Minus = "Minus",
    Period = "Period",
    Quote = "Quote",
    RightBracket = "RightBracket",
    Semicolon = "Semicolon",
    Slash = "Slash",
    Space = "Space",

    // numpad keys
    Numpad0 = "Numpad0",
    Numpad1 = "Numpad1",
    Numpad2 = "Numpad2",
    Numpad3 = "Numpad3",
    Numpad4 = "Numpad4",
    Numpad5 = "Numpad5",
    Numpad6 = "Numpad6",
    Numpad7 = "Numpad7",
    Numpad8 = "Numpad8",
    Numpad9 = "Numpad9",
    NumpadDecimal = "NumpadDecimal",
    NumpadDivide = "NumpadDivide",
    NumpadMultiply = "NumpadMultiply",
    NumpadSubtract = "NumpadSubtract",
    NumpadAdd = "NumpadAdd",
    NumpadEnter = "NumpadEnter",
    NumpadEqual = "NumpadEqual",

    // function keys
    AltLeft = "AltLeft",
    AltRight = "AltRight",
    Backspace = "Backspace",
    CapsLock = "CapsLock",
    ContextMenu = "ContextMenu",
    ControlLeft = "ControlLeft",
    ControlRight = "ControlRight",
    Delete = "Delete",
    DownArrow = "DownArrow",
    End = "End",
    Escape = "Escape",
    Home = "Home",
    Insert = "Insert",
    LeftArrow = "LeftArrow",
    MetaLeft = "MetaLeft",
    MetaRight = "MetaRight",
    NumLock = "NumLock",
    PageDown = "PageDown",
    PageUp = "PageUp",
    Pause = "Pause",
    PrintScreen = "PrintScreen",
    RightArrow = "RightArrow",
    ScrollLock = "ScrollLock",
    ShiftLeft = "ShiftLeft",
    ShiftRight = "ShiftRight",
    Tab = "Tab",
    UpArrow = "UpArrow",

    F1 = "F1",
    F2 = "F2",
    F3 = "F3",
    F4 = "F4",
    F5 = "F5",
    F6 = "F6",
    F7 = "F7",
    F8 = "F8",
    F9 = "F9",
    F10 = "F10",
    F11 = "F11",
    F12 = "F12",
    F13 = "F13",
    F14 = "F14",
    F15 = "F15",
    F16 = "F16",
    F17 = "F17",
    F18 = "F18",
    F19 = "F19",
    F20 = "F20",
    F21 = "F21",
    F22 = "F22",
    F23 = "F23",
    F24 = "F24",
    F25 = "F25",
}

/**
 * An enum containing most of the mouse button codes from event.button.
 * This is here to easily get autocomplete info for mouse button codes.
 *
 * @memberof ESSEM
 */
export enum MouseCode {
    Button0 = 0,
    Button1 = 1,
    Button2 = 2,
    Button3 = 3,
    Button4 = 4,
    Button5 = 5,
    Button6 = 6,
    Button7 = 7,

    ButtonLeft = Button0,
    ButtonRight = Button1,
    ButtonMiddle = Button2,
    ButtonLast = Button7,
}
