name: Node Continuous Intergration

on:
    push:
        branches: [ '**' ]
        tags: [ '**' ]
    pull_request:
        branches: [ '**' ]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v1
              with: 
                  node-version: 12.x
            - name: Install yarn and xvfb
              run: npm install -g yarn && sudo apt-get install xvfb
            - name: Install dependencies
              run: yarn install
            - name: Lint code
              run: yarn run lint
            - name: Build library
              run: yarn run build
            - name: Run Unit Tests
              run: xvfb-run --auto-servernum yarn run test
