name: Node Continuous Intergration

on:
    push:
        branches: ["**"]
        tags: ["**"]
        pull_request:
            branches: ["**"]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 20.x
            - name: Install pnpm and xvfb
              run: npm install -g pnpm && sudo apt-get install xvfb
            - name: Install dependencies
              run: pnpm install
            - name: Build library
              run: pnpm build
            - name: Run Unit Tests
              run: xvfb-run --auto-servernum pnpm test
            - name: Lint code
              run: pnpm lint:fix
            - name: Commit changes
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: Run lint fix
                  branch: ${{ github.head_ref }}
